title: Megan McKay # your name (or website title) here
logo: "/images/Headshot2020 white background.jpg?raw=true" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
 Hi, I'm Megan McKay a Data Analyst and Math Educator.  <br><br>
 Breaking down complex topics in digestible terms. 
Articulating data-driven decisions that produce positive change!  <br><br>
  <a href="https://www.linkedin.com/in/megan-a-mckay/">View My LinkedIn Profile</a> 
  # Quick Links
  - Excel Project
  - Tableau Project
  - SQL Project
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
